steps:
  # ==============================================================================
  # 1. BUILD & CACHE
  # ==============================================================================
  # We use the 'docker' builder.
  # Best Practice: We pull 'latest' first to use as a cache layer. 
  # This speeds up builds significantly by reusing existing layers.
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:latest || exit 0

  # ==============================================================================
  # 2. BUILD THE IMAGE
  # ==============================================================================
  # We tag with BOTH the Commit SHA (for versioning) and 'latest' (for convenience).
  # We use --cache-from to use the image we just pulled.
  # - name: 'gcr.io/cloud-builders/docker'
  # - name: 'docker:27' 
  #   args:
  #     - 'build'
  #     - '--network=cloudbuild'
  #     - '--platform=linux/amd64' 
  #     - '--no-cache'
  #     - '-t'
  #     - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
  #     - '-t'
  #     - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:latest'
  #     - '.'
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
      - '--destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '--dockerfile=Dockerfile'
      - '--context=dir://.'
      - '--cache=true'
      - '--cache-ttl=24h'
  # ==============================================================================
  # 3. PUSH IMAGES
  # ==============================================================================
  # Push both tags.
  # - name: 'gcr.io/cloud-builders/docker'
  #   args:
  #     - 'push'
  #     - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
  
  # - name: 'gcr.io/cloud-builders/docker'
  #   args:
  #     - 'push'
  #     - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:latest'

  # ==============================================================================
  # 4. DEPLOY TO CLOUD RUN JOB
  # ==============================================================================
  # Update the job to use the specific SHA we just built.
  # Best Practice: Always deploy the SHA, not 'latest', so you know exactly what is running.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - '${_JOB_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
      - '--region=${_REGION}'

substitutions:
  _REGION: asia-southeast1       
  _REPO_NAME: n8n-batch-repo     
  _JOB_NAME: n8n-daily-tldr      
  _IMAGE_NAME: n8n-custom       
logsBucket: 'gs://serious-hobbies-cloudbuild-logs'
options:
  logging: GCS_ONLY
timeout: 3600s
